version: "3.8"

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: snu_postgres
    restart: always
    environment:
      POSTGRES_USER: snu_admin
      POSTGRES_PASSWORD: snu_password_123
      POSTGRES_DB: snu_admissions_db
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: